## Page4：模块导入

In [1]:
import numpy as np

## Page7：数组函数

In [2]:
List=[1,2,3,4]
arr=np.array(List)
arr

array([1, 2, 3, 4])

In [3]:
arr=np.array(List,dtype=float)
arr

array([1., 2., 3., 4.])

In [4]:
arr=np.array(List,dtype=float,ndmin=3)
arr

array([[[1., 2., 3., 4.]]])

In [8]:
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

4
(1, 1, 4)
3
float64


## Page8：规律数组函数

In [12]:
a1=np.arange(1, 5, 2, dtype=None)
print('使用arange生成数组:', a1)
a12=np.arange(1, 5, dtype=None)
print('使用arange生成数组(不设置步长):', a12)
a13=np.arange(5, dtype=None)
print('使用arange生成数组(不设置步长和起始值):', a13)

使用arange生成数组: [1 3]
使用arange生成数组(不设置步长): [1 2 3 4]
使用arange生成数组(不设置步长和起始值): [0 1 2 3 4]


In [13]:
b=np.linspace(2.0, 3.0)
print('使用linspace生成数组,默认状态\n',b)
b=np.linspace(2.0, 3.0, num=5, retstep=True,endpoint=False)
print('使用linspace生成数组,显示间距,不使用endpoint\n',b)
b=np.linspace(2.0, 3.0, num=5, retstep=True, endpoint=True)
print('使用linspace生成数组,显示间距,使用endpoint\n',b)
b=np.linspace(2.0, 3.0, num=5, endpoint=True)
print('使用linspace生成数组,不显示间距,使用endpoint\n',b)

使用linspace生成数组,默认状态
 [2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]
使用linspace生成数组,显示间距,不使用endpoint
 (array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)
使用linspace生成数组,显示间距,使用endpoint
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)
使用linspace生成数组,不显示间距,使用endpoint
 [2.   2.25 2.5  2.75 3.  ]


In [14]:
a=np.linspace(1, 5, num=5, endpoint=True)
print('生成一个linspace数组\n',a)
b1=np.logspace(1, 5, num=5, endpoint=True, base=2.0, dtype=None)
print('上述linspace数组对应的logspace数组\n',b1)

生成一个linspace数组
 [1. 2. 3. 4. 5.]
上述linspace数组对应的logspace数组
 [ 2.  4.  8. 16. 32.]


## Page9：简便的数组生成函数

In [15]:
n=3
arr=np.array([[1,2],[3,4]])

In [16]:
print(np.ones(n))
print(np.ones((n,n)))
print(np.ones_like(arr))

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1]
 [1 1]]


## Page10：随机数模块

In [22]:
a=np.random.randint(1,5)
print('生成一个随机整数\n',a)
arr=np.random.randint(1,5,size=(2,3))
print('生成一个随机数组\n',arr)
arr=np.random.randint(1,5,(2,3))
print('size可以不写\n',arr)

生成一个随机整数
 4
生成一个随机数组
 [[3 4 4]
 [4 1 1]]
size可以不写
 [[4 2 2]
 [1 4 1]]


In [25]:
print('生成一个数\n',np.random.random())
print('生成一个一维数组\n',np.random.random(3))
print('生成一个二维数组\n',np.random.random((3,2)))

生成一个数
 0.634779840768332
生成一个一维数组
 [0.44881329 0.53315786 0.28831474]
生成一个二维数组
 [[0.58942783 0.55792818]
 [0.59935275 0.20314186]
 [0.8385725  0.25198153]]


## Page11：随机数模块

In [29]:
np.random.seed(1) 
a=np.random.random()
np.random.seed(1) 
b=np.random.random()
print('使用seed可以指定随机数',a,b)

使用seed可以指定随机数 0.417022004702574 0.417022004702574


In [37]:
arr=np.arange(1,8)
print(arr)
arr2=np.random.permutation(arr)
print('打乱顺序后的数组\n',arr2)

[1 2 3 4 5 6 7]
打款顺序后的数组
 [4 5 1 7 6 3 2]


In [40]:
arr =np.arange(1,8)
print(arr)
np.random.shuffle(arr)
print(arr)
#函数shuffle与permutation都是对原来的数组进行重新洗牌（即随机打乱原来的元素顺序）；
#区别在于shuffle直接在原来的数组上进行操作，改变原来数组的顺序，无返回值。
#而permutation不直接在原来的数组上进行操作，而是返回一个新的打乱顺序的数组，并不改变原来的数组。


[1 2 3 4 5 6 7]
[4 1 3 2 5 7 6]


## Page12：数据的读写

In [136]:
arr=np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8],
              [7, 8, 9, 10, 11]])
np.save("save_arr",arr)
print('加载已保存的npy文件',np.load("save_arr.npy"))

arr1=np.array([[0, 0, 0, 0, 0],
              [4, 5, 6, 7, 8],
              [7, 8, 9, 10, 11]])
np.savez("save_arrz.npy",arr,arr1)
data=np.load("save_arrz.npy.npz")
print('查看已保存的npy.npz文件的目录\n',data.files)
print('查看npy.npz文件中arr_1的数据\n',data['arr_1'])

加载已保存的npy文件 [[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]
查看已保存的npy.npz文件的目录
 ['arr_0', 'arr_1']
查看npy.npz文件中arr_1的数据
 [[ 0  0  0  0  0]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]


In [137]:
np.savez("save_arrz1.npz",test1=arr,第二格表=arr1)
data1=np.load("save_arrz1.npz")
print('查看已保存的npz文件的目录\n',data1.files)

查看已保存的npz文件的目录
 ['test1', '第二格表']


In [138]:
np.savetxt("arr.txt", arr, fmt="%d", delimiter=" ")
print('加载用空格键分隔保存txt文件\n',np.loadtxt("arr.txt",delimiter=" "))
print('加载用空格键分隔保存txt文件\n',np.genfromtxt("arr.txt", delimiter = " "))

加载用空格键分隔保存txt文件
 [[ 1.  2.  3.  4.  5.]
 [ 4.  5.  6.  7.  8.]
 [ 7.  8.  9. 10. 11.]]
加载用空格键分隔保存txt文件
 [[ 1.  2.  3.  4.  5.]
 [ 4.  5.  6.  7.  8.]
 [ 7.  8.  9. 10. 11.]]


## Page14：数组索引与切片

In [139]:
arr=np.array([1, 2, 3, 4, 5, 6])
print('原始数组\n',arr)
print('访问数组中索引为0的值\n',arr[0])
print('访问数组中索引为1:3的值(不包括3)\n',arr[1:3])
print('通过索引列表访问数组\n',arr[[0,2,4]])
print('通过一定规律访问数组\n',arr[1:5:2])
print('反向访问数组\n',arr[5:1:-2])
print('访问数组最后一个值\n',arr[-1])
print('从末尾开始访问数组\n',arr[-1:-4:-1])

原始数组
 [1 2 3 4 5 6]
访问数组中索引为0的值
 1
访问数组中索引为1:3的值(不包括3)
 [2 3]
通过索引列表访问数组
 [1 3 5]
通过一定规律访问数组
 [2 4]
反向访问数组
 [6 4]
访问数组最后一个值
 6
从末尾开始访问数组
 [6 5 4]


In [140]:

arr=np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8],
              [7, 8, 9, 10, 11]])
print('原始数组\n',arr)
print('访问某个元素示例\n',arr[1,0])
print('访问多个元素示例1:第二行第二三个元素\n',arr[1,1:3])
print('访问多个元素示例2:第二行第一三四个元素\n',arr[1,[0,2,3]])
print('访问多个元素示例2\n',arr[1,1:5:2])
print('访问多个元素示例2\n',arr[1:3,5:1:-2])
print('访问数列第二行\n',arr[1,:])
print('访问数列第四列\n',arr[:,3])

原始数组
 [[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]
访问某个元素示例
 4
访问多个元素示例1:第二行第二三个元素
 [5 6]
访问多个元素示例2:第二行第一三四个元素
 [4 6 7]
访问多个元素示例2
 [5 7]
访问多个元素示例2
 [[ 8  6]
 [11  9]]
访问数列第二行
 [4 5 6 7 8]
访问数列第四列
 [ 4  7 10]


## Page15：布尔数组

In [141]:
arr1=np.random.randint(1,8,(5,4))
arr2=np.random.randint(1,8,(5,4))
b_arr=arr2>arr1
print(b_arr)

[[ True False False  True]
 [False  True  True  True]
 [ True False False  True]
 [ True False  True  True]
 [False  True  True False]]


In [142]:
print('n_arr所有元素为真的个数\n',b_arr.sum())
print('n_arr每列元素为真的个数\n',b_arr.sum(axis=0))
print('n_arr每行元素为真的个数\n',b_arr.sum(axis=1))

n_arr所有元素为真的个数
 12
n_arr每列元素为真的个数
 [3 2 3 4]
n_arr每行元素为真的个数
 [2 3 2 3 2]


In [143]:
print('检查数组里有没有ture\n',b_arr.any())
print('检查数组里是不是都是ture\n',b_arr.all())

检查数组里有没有ture
 True
检查数组里是不是都是ture
 False


## Page16：布尔索引与切片

In [144]:
arr1D=np.random.randint(1,8,5)
print('直接使用布尔值提取一维数组的元素\n',
      arr1D[[False,False,True,False,True]])

直接使用布尔值提取一维数组的元素
 [1 7]


In [145]:
arr2D=np.random.randint(1,8,(5,4))
print('直接使用布尔值提取二维数组的行/列元素',
      '\n行\n',
    arr2D[[False,False,True,False,True],:],
      '\n列\n',
     arr2D[:,[False,True,False,True]])

直接使用布尔值提取二维数组的行/列元素 
行
 [[4 7 6 2]
 [2 1 5 1]] 
列
 [[5 5]
 [6 1]
 [7 2]
 [4 4]
 [1 1]]


In [146]:
print('直接使用布尔值提取二维数组的单个元素\n',
     arr2D[b_arr],
      '\n提取后元素返回成一个一维数组')

直接使用布尔值提取二维数组的单个元素
 [4 5 6 2 1 4 2 3 7 4 1 5] 
提取后元素返回成一个一维数组


## Page17：数组计算

In [147]:
arr1=np.random.randint(-5,5,(5,5))
arr2=np.random.randint(-5,5,(5,5))
print(arr1+arr2)
print(arr1/arr2)

[[-5  3 -8 -5  3]
 [-1  5 -5 -5 -2]
 [ 0 -6  8  1 -9]
 [ 1  5  0 -3  0]
 [ 1 -3 -8 -6 -4]]
[[ 4.          2.          1.         -0.         -0.25      ]
 [-0.          0.25        1.5        -0.                -inf]
 [-1.          0.5         1.          0.          0.8       ]
 [-1.33333333  0.66666667 -1.         -2.5        -1.        ]
 [        inf -4.          0.6         5.          0.33333333]]


<ipython-input-147-fd9556b6dfd8>:4: RuntimeWarning: divide by zero encountered in true_divide
  print(arr1/arr2)


### 一元通用函数举例

In [148]:
np.abs(arr1)

array([[4, 2, 4, 0, 1],
       [0, 1, 3, 0, 2],
       [4, 2, 4, 0, 4],
       [4, 2, 2, 5, 3],
       [1, 4, 3, 5, 1]])

In [149]:
np.log(np.abs(arr1))

<ipython-input-149-5201574b8517>:1: RuntimeWarning: divide by zero encountered in log
  np.log(np.abs(arr1))


array([[1.38629436, 0.69314718, 1.38629436,       -inf, 0.        ],
       [      -inf, 0.        , 1.09861229,       -inf, 0.69314718],
       [1.38629436, 0.69314718, 1.38629436,       -inf, 1.38629436],
       [1.38629436, 0.69314718, 0.69314718, 1.60943791, 1.09861229],
       [0.        , 1.38629436, 1.09861229, 1.60943791, 0.        ]])

In [150]:
np.sign(arr)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 二元通用函数举例

In [151]:
np.add(arr1,arr2)

array([[-5,  3, -8, -5,  3],
       [-1,  5, -5, -5, -2],
       [ 0, -6,  8,  1, -9],
       [ 1,  5,  0, -3,  0],
       [ 1, -3, -8, -6, -4]])

In [152]:
np.multiply(arr1,arr2)

array([[  4,   2,  16,   0,  -4],
       [  0,   4,   6,   0,   0],
       [-16,   8,  16,   0,  20],
       [-12,   6,  -4, -10,  -9],
       [  0,  -4,  15,   5,   3]])

## Page19：广播规则

In [153]:
print('一维数组与标量运算\n',np.arange(3)+5)
print('二维数组与一维数组运算\n',np.ones((3,3))+np.arange(3))
print('两个维度有1的数组运算\n',np.arange(3).reshape(3,1)+np.arange(3))

一维数组与标量运算
 [5 6 7]
二维数组与一维数组运算
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
两个维度有1的数组运算
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


## Page20：排序与唯一值

In [154]:
arr=np.array([5,6,7,0,3,2,1,4])
print('对arr进行正向排序\n',np.sort(arr))

arr=np.array([[1, 2, 5, 4, 3],
              [7, 8, 9, 10, 8],
              [4, 11, 6, 7, 5]])
print('原始数组\n',arr)
print('沿纵轴排序\n',np.sort(arr,axis=0))
print('沿横轴排序\n',np.sort(arr,axis=1))
print('返回值为重新排序值的下标\n',np.argsort(arr))

对arr进行正向排序
 [0 1 2 3 4 5 6 7]
原始数组
 [[ 1  2  5  4  3]
 [ 7  8  9 10  8]
 [ 4 11  6  7  5]]
沿纵轴排序
 [[ 1  2  5  4  3]
 [ 4  8  6  7  5]
 [ 7 11  9 10  8]]
沿横轴排序
 [[ 1  2  3  4  5]
 [ 7  8  8  9 10]
 [ 4  5  6  7 11]]
返回值为重新排序值的下标
 [[0 1 4 3 2]
 [0 1 4 2 3]
 [0 4 2 3 1]]


In [155]:
a = [1,5,1,4,3,4,4]
b = [9,4,0,4,0,2,1]
ind = np.lexsort((b,a)) # 先排a,后排b
print('以a为主要顺序进行排序的索引\n',ind)
[print([a[i],b[i]]) for i in ind]
a = np.array([1,5,1,4,3,4,4])
print('找出数组中的唯一值并返回已排序的结果\n',np.unique(a))

以a为主要顺序进行排序的索引
 [2 0 4 6 5 3 1]
[1, 0]
[1, 9]
[3, 0]
[4, 1]
[4, 2]
[4, 4]
[5, 4]
找出数组中的唯一值并返回已排序的结果
 [1 3 4 5]


## Page21：去重与重复数据

In [156]:
arr=np.array([5,6,7,0,3,2,1,4])
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [157]:
np.tile(arr,3)

array([5, 6, 7, 0, 3, 2, 1, 4, 5, 6, 7, 0, 3, 2, 1, 4, 5, 6, 7, 0, 3, 2,
       1, 4])

In [158]:
np.repeat(arr1,3,axis=0)

array([[-4,  2, -4,  0, -1],
       [-4,  2, -4,  0, -1],
       [-4,  2, -4,  0, -1],
       [ 0,  1, -3,  0, -2],
       [ 0,  1, -3,  0, -2],
       [ 0,  1, -3,  0, -2],
       [ 4, -2,  4,  0, -4],
       [ 4, -2,  4,  0, -4],
       [ 4, -2,  4,  0, -4],
       [ 4,  2,  2, -5,  3],
       [ 4,  2,  2, -5,  3],
       [ 4,  2,  2, -5,  3],
       [ 1, -4, -3, -5, -1],
       [ 1, -4, -3, -5, -1],
       [ 1, -4, -3, -5, -1]])

## Page22：统计函数

In [161]:
arr=np.array([5,6,7,0,3,2,1,4])
print('计算和\n'arr.sum())
print('计算平均值\n'arr.mean())
print('计算标准差\n'arr.std())
print('计算方差\n'arr.var())
print('计算最小值\n'arr.min())
print('计算最大值\n'arr.max())
print('计算最小值索引\n'arr.argmin())
print('计算最大值索引\n'arr.argmax())
print('计算累积和\n'arr.cumsum())
print('计算累积积\n'arr.cumprod())

array([  5,  30, 210,   0,   0,   0,   0,   0], dtype=int32)

## Page23：改变数组形状

In [163]:
arr=np.arange(12)
print('原始数组\n',arr)
print('更改数组成3×4\n',np.reshape(arr,(3,4)))
print('更改数组成3×4\n',arr.reshape((2,6)))

arr1=np.random.random((2,2))
arr2=np.random.random((2,2))
print('对两个数组横向组合\n',np.hstack((arr1,arr2)))

arr=np.random.random((4,4))
print('原始数组\n',arr)
print('数组横向分割\n',np.hsplit(arr,4))
print('数组纵向分割\n',np.split(arr,2,axis=0))


原始数组
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
更改数组成3×4
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
更改数组成3×4
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
对两个数组横向组合
 [[0.85931781 0.83039957 0.57849958 0.27411978]
 [0.6491542  0.67369842 0.56052999 0.67172978]]
原始数组
 [[0.35242963 0.85582837 0.19503749 0.74732081]
 [0.28960275 0.77379929 0.42773733 0.80769841]
 [0.35353486 0.21369324 0.76728451 0.30864195]
 [0.73324507 0.74447315 0.2213967  0.21411214]]
数组横向分割
 [array([[0.35242963],
       [0.28960275],
       [0.35353486],
       [0.73324507]]), array([[0.85582837],
       [0.77379929],
       [0.21369324],
       [0.74447315]]), array([[0.19503749],
       [0.42773733],
       [0.76728451],
       [0.2213967 ]]), array([[0.74732081],
       [0.80769841],
       [0.30864195],
       [0.21411214]])]
数组纵向分割
 [array([[0.35242963, 0.85582837, 0.19503749, 0.74732081],
       [0.28960275, 0.77379929, 0.42773733, 0.80769841]]), array([[0.35353486, 0.21369324, 0.76728451, 0.30864195],
       [0.7

## Page25：矩阵计算

In [165]:
A = np.mat('1 1; 1 0')
B = np.mat('2 2; 2 2')
C = np.mat('3 4; 5 6')
D = np.mat('7 8; 9 0')
print('四个矩阵的合并示例1\n',np.bmat([[A, B], [C, D]]))
print('四个矩阵的合并示例2\n',np.bmat('A,B; C,D'))
print('矩阵转置\n',A.T)


四个矩阵的合并示例1
 [[1 1 2 2]
 [1 0 2 2]
 [3 4 7 8]
 [5 6 9 0]]
四个矩阵的合并示例2
 [[1 1 2 2]
 [1 0 2 2]
 [3 4 7 8]
 [5 6 9 0]]
矩阵转置
 [[1 1]
 [1 0]]


## Page26：线性函数

In [166]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
#[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]
print(np.dot(a,b))

[[37 40]
 [85 92]]


In [167]:
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
 
print ('数组 a：')
print (a)
ainv = np.linalg.inv(a) 
 
print ('a 的逆：')
print (ainv)
 
print ('矩阵 b：')
b = np.array([[6],[-4],[27]]) 
print (b)
 
print ('计算：A^(-1)B：')
x = np.linalg.solve(a,b) 
print (x)
# 这就是线性方向 x = 5, y = 3, z = -2 的解

数组 a：
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
a 的逆：
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
矩阵 b：
[[ 6]
 [-4]
 [27]]
计算：A^(-1)B：
[[ 5.]
 [ 3.]
 [-2.]]
